version: "3.2"

volumes:
    db :
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/jeongwle/data/db'
    wp :
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/jeongwle/data/wp'
services:
    mariadb:
        container_name: mariadb
        build:
            context: requirements/mariadb/
            args:
                - ARG_MYSQL_USER=$MYSQL_USER
                - ARG_MYSQL_DATABASE=$MYSQL_DATABASE
                - ARG_MYSQL_PASSWORD=$MYSQL_PASSWORD
        restart: always
        expose:
            - "3306"
        volumes:
            - db:/var/lib/mysql/
        networks:
            - intra
        tty: true
        env_file:
            - ./.env
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build:
            context: requirements/nginx/
        restart: always
        ports:
            - "443:443"
        volumes:
            - wp:/var/www/html
        networks:
            - intra
        tty: true
        env_file:
            - ./.env
    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress/
            args:
                - ARG_MYSQL_USER=$MYSQL_USER
                - ARG_MYSQL_DATABASE=$MYSQL_DATABASE
                - ARG_MYSQL_PASSWORD=$MYSQL_PASSWORD
        restart: always
        volumes:
            - wp:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
        env_file:
            - ./.env
networks:
    intra:
        driver: bridge
