version: '3'

volumes:
    data: {}
services:
    mariadb:
        #image: debian:buster
        container_name: mariadb
        build:
            context: requirements/mariadb/
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        tty: true
        env_file:
            - .env
    nginx:
        #image: debian:buster
        container_name: nginx
        build:
            context: requirements/nginx/
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
        networks:
            - intra
        tty: true
    wordpress:
        #image: debian:buster
        container_name: wordpress
        build:
            context: requirements/wordpress/
        restart: always
        volumes:
            - data:/var/www/html
        expose:
            - "9000"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge
